### PR TITLE
pipeline improvements

### PR DESCRIPTION
**Pull request by helpmehelpus**
This PR contains changes to the pipeline that attempt to make it leaner. Its main changes are:

- filter by Java tags early on in the flow (other steps to address the consequences of this are added/upated)
- removes columns that should no longer be used, upon completion of steps that depended on them
- removes empty code blocks as soon as they are created

Unfortunately, there is not much else that can be done before the big `CoGroupByKey` is invoked (I was trying to filter the empty fields/lists before that as much as possible). But these changes should already cause some improvement. If anything, a bit less memory should be consumed

### CODE REVIEW

**Comment by helpmehelpus** [comment]
@sbaltes ran it using the test data. can you please take a look/run locally too and let me know if it's OK?

**Comment by sbaltes** [comment]
Thanks for the changes!
Could you resolve the conflicts?
Afterwards, I'll test everything locally.

**Comment by helpmehelpus** [comment]
> Thanks for the changes! Could you resolve the conflicts? Afterwards, I'll test everything locally.

I though I had solved them? Currently it reads 'this branch has no conflict with the base branch'

**Comment by helpmehelpus** [comment]
@sbaltes do you still see conflicts? I don't see any at the moment

**Pull request closed without merging**
