### PR TITLE
pipeline optimization

### PR DESCRIPTION
**Pull request by helpmehelpus**
creating a new PR to see if the conflicts are solved. I confused myself a bit with the forking

hopefully it's all good now @sbaltes

### CODE REVIEW

**Comment by sbaltes** [comment]
I've added two minor TODO. The conflict is still present. I tend to rebase the PRs before merging them: 
image
That's where the conflict comes from.
You need to pull from upstream (see, e.g., https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork), then rebase your changes, and push to the branch in your repo that is the basis for this PR.

**Comment by sbaltes** [comment]
This is how it looks like if you select "rebase and merge": 
image

**Comment by helpmehelpus** [comment]
well that's funny. when I try to sync with upstream, I am told there is nothing new for me to fetch

**Comment by helpmehelpus** [comment]
image

**Pull request closed without merging**
